const gulp = require('gulp')
const webpack = require('webpack')
const webpackStream = require('webpack-stream')
const webpackConfigProd = require('./prod.webpack.config.js')
const webpackConfigDev = require('./dev.webpack.config.js')
gulp.task('prod-webpack-setup', function () {
	return gulp.src('src/entry.js')
		.pipe(webpackStream(webpackConfigProd), webpack)
		.pipe(gulp.dest('./public/'))
})
gulp.task('dev-webpack-setup', function () {
	return gulp.src('src/entry.js')
		.pipe(webpackStream(webpackConfigDev), webpack)
		.pipe(gulp.dest('./public/'))
})
gulp.task('copy', function() {
	gulp.src('./frontEnd/src/theme/index.html')
		.pipe(gulp.dest('./public/'))
})
gulp.task('prod-webpack', ['prod-webpack-setup', 'copy'])
gulp.task('dev-webpack', ['dev-webpack-setup', 'copy'])