version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4-stretch
        environment:
          DB_USERNAME: mongousradmin
          DB_PASSWORD: mongopassadmin
      - image: circleci/mongo:3.4
        environment:
          MONGO_INITDB_ROOT_USERNAME: mongousradmin
          MONGO_INITDB_ROOT_PASSWORD: mongopassadmin
          MONGO_INITDB_DATABASE: container
      - image: cypress/base:8
    steps:
      - checkout
      - restore_cache:
          name: Restore cache (backend)
          keys:
          - v2-dependencies-{{ checksum "src/server/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - restore_cache:
          name: Restore cache (frontEnd)
          keys:
          - v2-dependencies-{{ checksum "src/server/frontEnd/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run:
          name: Cypress Dependencies
          command: sudo apt-get update && sudo apt-get install xvfb libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 --fix-missing

      - run: 
          name: Deployment (backend)
          command: npx gulp installServerDependencies

      - run: 
          name: Deployment (frontEnd)
          command: npx gulp installFrontEndDependencies
          
      - save_cache:
          name: Saving cache (backend)
          paths:
            - src/server/node_modules
            - /home/circleci/.cache
            - /home/circleci/.npm
          key: v2-dependencies-{{ checksum "src/server/package.json" }}

      - save_cache:
          name: Saving cache (frontEnd)
          paths:
            - src/server/frontEnd/node_modules
          key: v2-dependencies-{{ checksum "src/server/frontEnd/package.json" }}

      - run:
          name: Static Analysis (backend & frontEnd)
          command: npx gulp eslint

      - run:
          name: Generate config file (backend)
          command: npx gulp generateConfig

      - run:
          name: Mocha tests (backend)
          command: npx gulp serverTest

      - run:
          name: Jest tests (frontEnd)
          command: npx gulp frontEndTestCoverage

      - run:
          name: Push coverage to Codecov
          command: npx codecov

      - run: 
          name: Deployment (frontEnd) - Webpack
          command: npx gulp buildDev
          
      - run:
          name: Start NodeJS
          command: npx gulp start
          background: true

      - run:
          name: E2E tests
          command: npx gulp testCypress

      - store_artifacts:
          path: /home/circleci/project/src/server/.tests/cypress/videos
      - store_artifacts:
          path: /home/circleci/project/src/server/.tests/cypress/screenshots

      - run:
          name: Print the Current Time
          command: date

