version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
        environment:
          MONGO_INITDB_ROOT_USERNAME: mongousradmin
          MONGO_INITDB_ROOT_PASSWORD: mongopassadmin
          MONGO_INITDB_DATABASE: container
      - image: circleci/mongo:3.4.4
        environment:
          MONGO_INITDB_ROOT_USERNAME: mongousradmin
          MONGO_INITDB_ROOT_PASSWORD: mongopassadmin
          MONGO_INITDB_DATABASE: container
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "src/server/package.json" }}
          - v2-dependencies-{{ checksum "src/client/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
          - v2-dependencies-

      - run: 
          name: Deployment (backend)
          command: cd src/server && npm install

      - run: 
          name: Deployment (frontend)
          command: cd src/client && npm install

      - save_cache:
          paths:
            - src/server/node_modules
          key: v1-dependencies-{{ checksum "src/server/package.json" }}

      - save_cache:
          paths:
            - src/client/node_modules
          key: v2-dependencies-{{ checksum "src/client/package.json" }}

      - run:
          name: Static Analysis (backend)
          command: node ./src/server/node_modules/eslint/bin/eslint.js -c ./src/server/.eslintrc.json --ignore-path ./src/server/.eslintignore ./src/server

      - run:
          name: Mocha tests (backend)
          command: cd src/server/ && npm run test-coverage

      - run:
          name: Mocha tests (frontend)
          command: cd src/client/ && npm run test

      - run:
          name: Print the Current Time
          command: date

