version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
      - image: mongo:3.4.4
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle-test_test
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "src/server/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: 
          name: Deployment
          command: cd src/server && npm install

      - save_cache:
          paths:
            - src/server/node_modules
          key: v1-dependencies-{{ checksum "src/server/package.json" }}

      - run:
          name: Static Analysis (EsLint)
          command: node ./src/server/node_modules/eslint/bin/eslint.js -c ./src/server/.eslintrc.json --ignore-path ./src/server/.eslintignore ./src/server

      - run:
          name: Mocha tests
          command: cd src/server/ && npm test

      - run:
          name: Print the Current Time
          command: date

