version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4-stretch
        environment:
          DB_USERNAME: mongousradmin
          DB_PASSWORD: mongopassadmin
          EMAIL_HOST: localhost
          EMAIL: dummy@em.com
          EMAIL_PORT: 25
          EMAIL_PASSWORD: dommuPass
      - image: circleci/mongo:3.4
        environment:
          MONGO_INITDB_ROOT_USERNAME: mongousradmin
          MONGO_INITDB_ROOT_PASSWORD: mongopassadmin
          MONGO_INITDB_DATABASE: container
      - image: cypress/base:8
      - image: schickling/mailcatcher
    steps:
      - checkout
      - restore_cache:
          name: Restore cache (backend)
          keys:
          - v2-dependencies-{{ checksum "src/server/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - restore_cache:
          name: Restore cache (frontEnd)
          keys:
          - v2-dependencies-{{ checksum "src/server/frontEnd/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run:
          name: Cypress Dependencies
          command: sudo apt-get update && sudo apt-get install xvfb libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 --fix-missing

      - run: 
          name: Deployment (backend)
          command: cd src/server && npm install

      - run: 
          name: Deployment (frontEnd)
          command: cd src/server/frontEnd && npm install
          
      - save_cache:
          name: Saving cache (backend)
          paths:
            - src/server/node_modules
            - /home/circleci/.cache
            - /home/circleci/.npm
          key: v2-dependencies-{{ checksum "src/server/package.json" }}

      - save_cache:
          name: Saving cache (frontEnd)
          paths:
            - src/server/frontEnd/node_modules
          key: v2-dependencies-{{ checksum "src/server/frontEnd/package.json" }}

      - run:
          name: Static Analysis (backend & frontEnd)
          command: cd src/server && npm run eslint

      - run:
          name: Generate config file (backend)
          command: cd src/server && npm run generate-config

      - run:
          name: Mocha tests (backend)
          command: cd src/server/ && npm run test-coverage

      - run:
          name: Jest tests (frontEnd)
          command: cd src/server/frontEnd/ && npm run test-coverage

      - run:
          name: Push coverage to Codecov
          command: npx codecov

      - run: 
          name: Deployment (frontEnd) - Webpack
          command: cd src/server/ && npm run build-dev
          
      - run:
          name: Start NodeJS
          command: cd src/server/ && npm start
          background: true

      - run:
          name: E2E tests
          command: cd src/server/ && npx cypress run

      - store_artifacts:
          path: /home/circleci/project/src/server/.tests/cypress/videos
      - store_artifacts:
          path: /home/circleci/project/src/server/.tests/cypress/screenshotsi
      - store_artifacts:
          path: /home/circleci/project/src/server/logs
      - store_artifacts:
          path: /home/circleci/project/src/server/config.json

      - run:
          name: Print the Current Time
          command: date

