version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
        environment:
          DB_USERNAME: mongousradmin
          DB_PASSWORD: mongopassadmin
      - image: circleci/mongo:3.4
        environment:
          MONGO_INITDB_ROOT_USERNAME: mongousradmin
          MONGO_INITDB_ROOT_PASSWORD: mongopassadmin
          MONGO_INITDB_DATABASE: container
    steps:
      - checkout
      - restore_cache:
          name: Restore cache (backend)
          keys:
          - v1-dependencies-{{ checksum "src/server/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - restore_cache:
          name: Restore cache (frontend)
          keys:
          - v1-dependencies-{{ checksum "src/server/frontEnd/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: 
          name: Deployment (backend)
          command: cd src/server && npm install

      - run: 
          name: Deployment (frontend)
          command: cd src/server/frontEnd && npm install

      - save_cache:
          name: Saving cache (backend)
          paths:
            - src/server/node_modules
          key: v1-dependencies-{{ checksum "src/server/package.json" }}

      - save_cache:
          name: Saving cache (frontend)
          paths:
            - src/server/frontEnd/node_modules
          key: v1-dependencies-{{ checksum "src/server/frontEnd/package.json" }}

      - run:
          name: Static Analysis (backend & frontend)
          command: cd src/server && npm run eslint

      - run:
          name: Generate config file (backend)
          command: cd src/server && npm run generate-config

      - run:
          name: Mocha tests (backend)
          command: cd src/server/ && npm run test-coverage

      - run:
          name: Jest tests (frontend)
          command: cd src/server/frontEnd/ && npm run test-coverage

      - run:
          name: Print the Current Time
          command: date

